---
title: "Case Study 08"
author: "Zixuan Chen"
date: "Oct. 26 2020"
always_allow_html: true
output:
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---
```{r eval=T, message=F, warning= F, echo=FALSE, results='hide'}
library(ggplot2)
library(tidyverse)
library(knitr)
library(kableExtra)
d = read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt",
               skip = 56)%>%
  select(year,mean)

p1 = ggplot(d, aes(year, mean))+
  geom_line(color = "red")+
  labs(x = "Year",
       y = "Maunal Loa Annual Mean CO_2 (ppm)",
       title = "Annual Mean Carbon Dioxide Concentrations 1959-Present")
plot(p1)
```

```{r eval=T, message=F, warning= F, echo=F}
library(magick)
d%>%
  top_n(5)%>%
  arrange(desc(year))%>%
  kable(align = "ll",
        caption = "Top Five Annual Mean Carbon Dioxide Concentrations at Mona Loa")%>%
  kable_styling()%>%
  row_spec(1,bold = T, color = "red")%>%
  as_image(width = 10,file = "table.png")
```